id: I6C824809
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T01:03:29+00:00'
last_modified: '2022-06-07T16:53:42.789703+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG01644
  title: ཙཱ་འདྲ་གནས་འདུས་སྒོ་བྱང
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B96E:
      image_group_id: I00KG02947
      title: ''
      total_pages: 14
      order: 1
      base_file: B96E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
