id: P002999
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W00KG01644
  title: ཙཱ་འདྲ་གནས་འདུས་སྒོ་བྱང
  author: ''
  volumes:
    adfbaf32bfb149bebdfdb54cad075205:
      image_group_id: I00KG02947
      title: ''
      volume_number: 1
      total_pages: 14
      base_file: v001.txt
