id: P002999
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 10:33:30.381380
source_metadata:
  id: bdr:W00KG01644
  title: ཙཱ་འདྲ་གནས་འདུས་སྒོ་བྱང
  author: ''
  volumes:
    adfbaf32bfb149bebdfdb54cad075205:
      image_group_id: I00KG02947
      title: ''
      volume_number: 1
      total_pages: 14
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
